name: safe_change_notifier
description: A safe ChangeNotifier that keeps track of its disposal.
version: 0.0.1
homepage: https://github.com/jpnurmi/safe_change_notifier
repository: https://github.com/jpnurmi/safe_change_notifier
issue_tracker: https://github.com/jpnurmi/safe_change_notifier/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
